cloud_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('cloud_application.urls', namespace='cloud_application')),
    
]

cloud_application/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^display_airpollution$', airpollution, name='display_airpollution'),
]

cloud_application/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class AirPollution(models.Model):
    #Type = models.CharField(max_length=200)
    country = models.CharField(max_length=200)
    state = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    place = models.CharField(max_length=200)
    pollutants = models.CharField(max_length=200)
    
    def __str__(self):
        """Return a string representation of the model."""
        return self.pollutants

cloud_application/forms.py
from django import forms


class AirpollutionForm(forms.ModelForm):
    class meta:
        model = AirPollution
        feilds = ('country', 'state', 'city', 'place', 'pollution')

cloud_application/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from .models import *

# Create your views here.
def index(request):
    return render(request,'index.html')

def airpollution(request):
    items=AirPollution.objects.all()
    context={
    'items' : items,
    'header' : 'AirPollution'
    }
    return render(request, 'index.html', context)
    

cloud_application/templates/base.html
<html>

	<head>
		<title>Climate Change Concerns</title>
	</head>
	{% load static %}
	<link href="{% static 'css/style.css' %}" rel="stylesheet">
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	
	<body>
	<nav class="navbar navbar-expand navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Climate Change Concerns - We Act Now </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample02">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-md-0">
          <input class="form-control" type="text" placeholder="Search">
        </form>
      </div>
    </nav>
	
	<div class="container">
	{% block body %}
	
	{% endblock body %}
	</div>
	
	</body>
	
	
</html>

cloud_application/templates/index.html
{% extends 'base.html' %}

{% block body %}
<br>
<div class="button-group">
<a href="{% url 'cloud_application:display_airpollution' %}" class ="btn btn-primary btn-md" role="button"> AirPollution </a>
<a href="#" class ="btn btn-primary btn-md" role="button"> WaterPollution </a>
<a href="#" class ="btn btn-primary btn-md" role="button"> Toxic Gases </a>
</div>

<br>

<h4>Currently Viewing {{header}}</h4>
<table class="table table-hover">


<thead>
<tr>
<td>country</td>
<td>state</td>
<td>city</td>
<td>palce</td>
<td>pollutants</td>
</tr>
</thead>


<tbody>

{% for item in items %}
<tr>
<td>{{item.country}}</td>
<td>{{item.state}}</td>
<td>{{item.city}}</td>
<td>{{item.place}}</td>
<td>{{item.pollutants}}</td>
</tr>
{% endfor %}

</tbody>


</table>
{% endblock %}